---
title: "Enroll"
---

Thanks for your interest in the West Plains PFAS Filter Study! Here's the process to participate.

## Phase 1 - 60 households

Phase 1 will test the effectiveness of 60 filters already installed in households on the West Plains. To enroll:

1.  **Fill out the eligibility screening form.** This form will collect some initial information about your well and any existing water treatment systems in your home to determine if you are eligible. Our team will review the eligibility form and reach out to you for the formal enrollment process if your home fits the study criteria.

    -   **Fill out the eligibility screening form [here](https://cuboulder.qualtrics.com/jfe/form/SV_eb5mSeDAYBKopQq).**

2.  **Complete the enrollment survey.** If you are eligible to enroll, we will send you a link to a online survey. This survey will collect:

    -   Your formal agreement to participate in the study (consent).
    -   Information about water use in your household
    -   Information about your perceptions of PFAS contamination and the effectiveness of different responses.

3.  **Collect water samples.** Once we have your formal enrollment survey, we will send you a kit via FedEx with instructions to collect water samples from your filtered and unfiltered water. The kit will include a pre-paid return shipping label for you to mail the samples back to the University of Colorado Boulder.

## Phase 2 - 12 households

Phase 2 will install new systems in 12 households with high PFAS levels and test them over time. To enroll:

1.  **Fill out the eligibility screening form.** Same as above, this form will collect some initial information about your well and any existing water treatment systems in your home to determine if you are eligible. Our team will review the eligibility form and reach out to you for the formal enrollment process if your household fits the study criteria.

    -   **Fill out the eligibility screening form [here](https://cuboulder.qualtrics.com/jfe/form/SV_eb5mSeDAYBKopQq).**

2.  **Complete the enrollment survey.** If you are eligible to enroll, you will be sent a link to a online survey. This survey will collect:

    -   Your formal agreement to participate in the study (consent).
    -   Information about water use in your household
    -   Information about your perceptions of PFAS contamination and the effectiveness of different responses.

3.  **Schedule filter install.** Once we have your formal enrollment survey, we will coordinate with you to schedule a date to install a new filter system certified to remove PFAS in your home.

4.  **Collect water samples.** Once the new system is installed, we will send you a kit via FedEx with instructions to collect water samples from your filtered and unfiltered water on three different occasions. We will monitor the water use to know when to send you the sample kits based on the filter's certified capacity. Each kit will include a pre-paid return shipping label for you to mail the samples back to the University of Colorado Boulder.
